services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/config.env
    environment:
      - NODE_ENV=development
      - DATABASE=mongodb://mongo:27017/crm
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
